### PR TITLE
Dev 7 test controller

### LINKED ISSUE #7: Tests for SL controller
We should have tests for the swarm learning server and client controllers that 

- test the respective functionality
- report line coverage
- run in a docker container in a one-step procedure

### PR DESCRIPTION
**Pull request by oleschwen**
Unit tests cover most of the code on top of NVFlare, the remaining methods of SwarmClientController will require more setup (see #9).

```
Name                              Stmts   Miss  Cover   Missing
---------------------------------------------------------------
__init__.py                           2      2     0%   1-2
gatherer.py                         134      0   100%
swarm_client_ctl.py                 332    218    34%   142-172, 201-220, 226-245, 251-268, 274-306, 312-338, 344-363, 372-404, 416-516, 522-540
swarm_server_ctl.py                  43      0   100%
test_gatherer.py                    183      0   100%
test_swarm_client_controller.py     114      0   100%
test_swarm_server_controller.py     142      0   100%
---------------------------------------------------------------
TOTAL                               950    220    77%
```

### CODE REVIEW

**Review by Ultimate-Storm — APPROVED** [review]
Approved – everything looks great!

**Comment by oleschwen** [comment]
Simulation mode should work again now.

**Comment by oleschwen** [comment]
Should be reviewed after #13 has been completed.

**Review by Ultimate-Storm — APPROVED** [review]
Looks good to me

**Pull request merged**
